export const ScreenNamesCustomer = {
  LOGIN: 'Login',
  WALKTHROUGHSCREEN: 'WalkThroughScreen',
  TABBAR: 'TabBar',
  HOME: 'HomeCatalogs',
  CATALOGUE: 'Catalogs',
  ORDER: 'Orders',
  PROFILE: 'My Account',
  FILTER: 'Filter',
  PRODUCTDETAILS: 'ProductDetails',
  PRODUCTDETAILSFROMSEARCH: 'ProductDetailsFromSearch',
  CARTVIEW: 'CartView',
  WISHLIST: 'WishList',
  ORDERDETAILS: 'OrderDetails',
  TRACKORDER: 'TrackOrder',
  LEDGER: 'Ledger',
  VIEWINVOICE: 'ViewInvoice',
  CANCELORDER: 'CancelOrder',
  WEBVIEW: 'ProductWebView',
  SHOWBRANDS: 'ShowBrands',
  NEWHOME: 'Home',
};
